package ru.zkir.urbaneye3d;

import org.junit.jupiter.api.Test;
import ru.zkir.easytext.io.MsgId;
import ru.zkir.easytext.io.MsgStr;
import ru.zkir.easytext.io.PoParser;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class I18nStatusTest {

    @Test
    void verifyAndReportTranslationStatus() throws IOException {
        Path poDir = Paths.get("po");
        Path potFile = poDir.resolve("urbaneye3d.pot");
        Path outputDir = Paths.get("target/classes/data");
        Path reportFile = Paths.get("docs/dev/translation-status.md");

        // 1. Read .pot file to get the master list of strings
        String potContent = Files.readString(potFile);
        Map<MsgId, MsgStr> masterStrings = PoParser.decodeToTranslations(potContent);
        int totalStrings = masterStrings.size();

        StringBuilder markdownBuilder = new StringBuilder();
        markdownBuilder.append("# Translation Status\n");
        markdownBuilder.append("This file is auto-generated by `I18nStatusTest.java` and shows the translation coverage for each language.\n");
        markdownBuilder.append("| Language | Code | Status | Coverage |\n");
        markdownBuilder.append("|---|---|---|---|\n");

        // 2. Find all .po files
        List<Path> poFiles;
        try (Stream<Path> stream = Files.list(poDir)) {
            poFiles = stream
                    .filter(p -> p.getFileName().toString().endsWith(".po"))
                    .collect(Collectors.toList());
        }

        // sort to create stable output
        Collections.sort(poFiles);

        // 3. Process each .po file
        for (Path poFile : poFiles) {
            String fileName = poFile.getFileName().toString();
            String langCode = fileName.substring(0, fileName.length() - 3);
            String languageName = getLanguageName(langCode); // Helper to get full name

            String poContent = Files.readString(poFile);
            Map<MsgId, MsgStr> translatedStrings = PoParser.decodeToTranslations(poContent);

            // Count only non-empty translations
            long translatedCount = translatedStrings.values().stream()
                    .filter(msgStr -> msgStr != null && !msgStr.strings().isEmpty() && !msgStr.strings().get(0).isEmpty())
                    .count();

            double coverage = (double) translatedCount / totalStrings * 100;

            markdownBuilder.append(String.format(Locale.ROOT, "| %s | `%s` | %d / %d | %.1f%% |\n",
                    languageName,
                    langCode,
                    translatedCount,
                    totalStrings,
                    coverage));

            // 4. Assert that the corresponding .lang file exists
            Path langFile = outputDir.resolve(langCode + ".lang");
            assertTrue(Files.exists(langFile),
                    "The .lang file for '" + langCode + "' is missing. Expected at: " + langFile.toAbsolutePath());
        }

        // 5. Write the report file
        Files.write(reportFile, markdownBuilder.toString().getBytes(StandardCharsets.UTF_8));
        System.out.println("Successfully generated translation status report at: " + reportFile);
    }

    private String getLanguageName(String code) {
        // Simple mapping for known languages
        switch (code) {
            case "en": return "English";
            case "ru": return "Russian";
            case "de": return "German";
            case "fr": return "French";
            case "sk": return "Slovak";
            case "it": return "Italian";
            case "id": return "Indonesian";
            case "kw": return "Cornish";
            // Add other languages here
            default: return code.toUpperCase();
        }
    }
}
