package ru.zkir.urbaneye3d;

import org.junit.jupiter.api.Test;
import ru.zkir.urbaneye3d.utils.TreeSpeciesDatabase;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;

public class TreeSpeciesReportTest {

    @Test
    void generateTreeSpeciesReport() throws IOException {
        TreeSpeciesDatabase db = TreeSpeciesDatabase.getInstance();
        Map<String, TreeSpeciesDatabase.SpeciesInfo> speciesMap = db.getSpeciesMap();
        
        List<String> sortedSpecies = new ArrayList<>(speciesMap.keySet());
        sortedSpecies.sort((s1, s2) -> {
            String clean1 = s1.replace("×", "").replaceAll("\\s+", " ").trim();
            String clean2 = s2.replace("×", "").replaceAll("\\s+", " ").trim();
            return clean1.compareTo(clean2);
        });

        StringBuilder sb = new StringBuilder();
        sb.append("# Tree Species Database\n\n");
        sb.append("This report lists all tree species known to the UrbanEye3D plugin. ");
        sb.append("For trees belonging to these species, the plugin automatically determines the `leaf_type` and `leaf_cycle` based on the data below if these tags are missing in OSM. ");
        sb.append("This information is then used to select the most realistic 3D texture for rendering.\n\n");
        sb.append("**Important:** The underlying data file (`src/main/resources/data/tree_species.csv`) is automatically maintained by the `misc` subproject. ");
        sb.append("It is compiled from the [OSM Wiki List of Species](https://wiki.openstreetmap.org/wiki/Tag:natural%3Dtree/List_of_Species) and the actual OSM data, ");
        sb.append("verified using [POWO API](https://powo.science.kew.org/). ");
        sb.append("To avoid regressions, **please do not edit the CSV file manually.** Instead, update the OSM Wiki or adjust the processing scripts in the `misc` directory.\n\n");
        sb.append("This report is auto-generated by `TreeSpeciesReportTest.java`.\n\n");
        sb.append("Total species count: ").append(speciesMap.size()).append("\n\n");
        
        sb.append("| Species | Genus | Leaf Cycle | Leaf Type | Wikidata |\n");
        sb.append("| :--- | :--- | :--- | :--- | :--- |\n");

        for (String speciesName : sortedSpecies) {
            TreeSpeciesDatabase.SpeciesInfo info = speciesMap.get(speciesName);
            String wikidataLink = (info.wikidata == null || info.wikidata.isEmpty()) ? "" : 
                String.format("[%s](https://www.wikidata.org/wiki/%s)", info.wikidata, info.wikidata);
            
            // Format species name with proper capitalization
            String formattedName = TreeSpeciesDatabase.formatSpecies(speciesName);

            sb.append(String.format("| *%s* | %s | %s | %s | %s |\n",
                    formattedName,
                    info.genus,
                    info.leafCycle,
                    info.leafType,
                    wikidataLink
            ));
        }

        Files.createDirectories(Paths.get("docs"));
        Files.write(Paths.get("docs/tree_species.md"), sb.toString().getBytes(StandardCharsets.UTF_8));
    }
}
