name: Upload Release Asset

on:
  release:
    types: [published]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to upload release assets
      packages: read  # Required to read campskeleton dependency from GitHub Packages

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up JDK 11
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - uses: actions/cache@v6
      env:
        cache-name: cache-maven-dependency
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-    

    - name: Build with Maven
      run: |
        VERSION=$(echo "${{ github.event.release.tag_name }}" | sed -e 's/^v//')
        mvn -B package -Drevision=$VERSION --file pom.xml -s $GITHUB_WORKSPACE/settings.xml -Dtest="!GroundPlaneTest"
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: gh release upload ${{ github.event.release.tag_name }} ./target/urbaneye3d.jar --clobber
